### ISSUE TITLE
Error detected while processing VimEnter Autocommands for "*"

### ISSUE THREAD

**Issue by charludo** [Pocco81/auto-save.nvim#37] opened 2022-08-02 09:30 UTC
In the current version, opening nvim produces the following error message:

```
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: ...cker/start/auto-save.nvim/lua/auto-save/utils/colors.lua:6: bad argument #1 to 'lower' (string expected, got nil)
stack traceback:
        [C]: in function 'lower'
        ...cker/start/auto-save.nvim/lua/auto-save/utils/colors.lua:6: in function 'hex_to_rgb'
        ...cker/start/auto-save.nvim/lua/auto-save/utils/colors.lua:51: in function 'darken'
        .../pack/packer/start/auto-save.nvim/lua/auto-save/init.lua:112: in function <.../pack/packer/start/auto-save.nvim/lua/auto-save/init.lua:106>
```

The plugin still performs as expected, however.

**Comment by kohane27** [comment] 2022-08-03 01:04
Duplicate of [Error with colors.lua · Issue #34 · Pocco81/auto-save.nvim](https://github.com/Pocco81/auto-save.nvim/issues/34)

**Comment by Pocco81** [comment] 2022-08-06 22:17
dup of #34.

**Closed by Pocco81** 2022-08-06 22:17 UTC
